import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1c1b1b",
        "border-default": "#EEEEEE",
        "primary-container": "#E8380D",
        "on-primary-container": "#fffbff",
        "on-secondary-fixed-variant": "#474646",
        "on-surface": "#1a1c1c",
        "tertiary-fixed": "#d6e3ff",
        "secondary-fixed": "#e5e2e1",
        "inverse-surface": "#2f3131",
        "surface-container-low": "#f3f3f4",
        "accent-border": "#FFCDC4",
        "secondary-container": "#e5e2e1",
        "tertiary-fixed-dim": "#aac7ff",
        "surface": "#FAFAFA",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f1",
        "accent-light": "#FFF2EF",
        "on-secondary-container": "#656464",
        "inverse-primary": "#ffb4a3",
        "whatsapp-green": "#25D366",
        "on-tertiary-fixed-variant": "#00468d",
        "background": "#f9f9f9",
        "primary": "#E8380D",
        "grade-a": "#22C55E",
        "grade-b": "#F97316",
        "grade-c": "#EF4444",
        "grade-d": "#475569",
        "grade-e": "#94A3B8",
        "surface-variant": "#e2e2e2",
        "soft-text": "#AAAAAA",
        "outline": "#916f67",
        "surface-dim": "#dadada",
        "on-tertiary-container": "#fefcff",
        "on-primary-fixed": "#3d0600",
        "surface-container": "#eeeeee",
        "primary-fixed": "#ffdad2",
        "outline-variant": "#e6bdb4",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary": "#005ab3",
        "on-surface-variant": "#5c4039",
        "on-primary-fixed-variant": "#8b1a00",
        "secondary": "#5f5e5e",
        "surface-container-high": "#e8e8e8",
        "error-container": "#ffdad6",
        "muted-text": "#888888",
        "on-secondary": "#ffffff",
        "tertiary-container": "#0073e0",
        "error": "#ba1a1a",
        "surface-tint": "#E8380D",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed": "#001b3e",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#ffb4a3",
        // Keeping some old tokens temporarily for safety if components still reference them
        "accent": "#E8380D",
        "whatsapp": "#25D366",
        "text-primary": "#111111",
        "text-muted": "#888888",
        "text-soft": "#AAAAAA",
        "bg-surface": "#FAFAFA",
      },
      fontFamily: {
        "body-sm": ["var(--font-inter)", "system-ui", "sans-serif"],
        "hero-md": ["var(--font-inter)", "system-ui", "sans-serif"],
        "card-title": ["var(--font-inter)", "system-ui", "sans-serif"],
        "hero-sm": ["var(--font-inter)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-inter)", "system-ui", "sans-serif"],
        "hero-lg": ["var(--font-inter)", "system-ui", "sans-serif"],
        "section-title-mobile": ["var(--font-inter)", "system-ui", "sans-serif"],
        "label-micro": ["var(--font-inter)", "system-ui", "sans-serif"],
        "section-title": ["var(--font-inter)", "system-ui", "sans-serif"],
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "1.5", letterSpacing: "0px", fontWeight: "400" }],
        "hero-md": ["36px", { lineHeight: "1.1", letterSpacing: "-1.5px", fontWeight: "500" }],
        "card-title": ["16px", { lineHeight: "1.4", letterSpacing: "0px", fontWeight: "500" }],
        "hero-sm": ["30px", { lineHeight: "1.1", letterSpacing: "-1.5px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "1.6", letterSpacing: "0px", fontWeight: "400" }],
        "hero-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-1.5px", fontWeight: "500" }],
        "section-title-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-1px", fontWeight: "500" }],
        "label-micro": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "section-title": ["32px", { lineHeight: "1.2", letterSpacing: "-1.5px", fontWeight: "500" }],
      },
      spacing: {
        "4": "4px",
        "8": "8px",
        "12": "12px",
        "16": "16px",
        "24": "24px",
        "32": "32px",
        "44": "44px",
        "60": "60px",
        "max-content-width": "1180px",
      },
      borderWidth: {
        "0.5": "0.5px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        btn: "8px",
        input: "8px",
        card: "14px",
        pill: "20px",
        "card-lg": "20px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};

export default config;
