const fs = require('fs');

const path = './src/messages/en.json';
const en = JSON.parse(fs.readFileSync(path, 'utf8'));

const translations = {
  seo: {
    ...en.seo,
    homeTitle: "We Buy Damaged Vehicles | Accident, Written-Off, Scrap Vehicle Purchase — Oto Grade",
    homeDescription: "Nationwide service for buying accident-damaged, written-off, burnt, flood-damaged and scrap vehicles. Free quote, doorstep pickup.",
    priceRange: "Free Quote",
    websiteDescription: "Nationwide damaged vehicle purchasing service",
    vehicleTypesTitle: "Damaged Vehicle Types — Accident, Written-Off, Scrap Vehicle Purchase | Oto Grade",
    vehicleTypesDescription: "We buy all types of damaged vehicles including accident-damaged, written-off, burnt, flood-damaged, scrap, and engine failure. Get a free quote.",
    aboutTitle: "About Us — Oto Grade",
    aboutDescription: "Learn about Oto Grade. Turkey's trusted address for damaged vehicle purchasing.",
    stat1: "Vehicles purchased",
    stat2: "Cities served",
    stat3Val: "1 hour",
    stat3: "Average response time",
    stat4: "Transparent process",
    val1Title: "Transparency",
    val1Desc: "No hidden fees, clear offers, open communication.",
    val2Title: "Speed",
    val2Desc: "Response within 1 hour, pickup within 24 hours.",
    val3Title: "Trust",
    val3Desc: "GDPR-compliant data processing, secure transfer process.",
    val4Title: "Accessibility",
    val4Desc: "Nationwide service, 7 days WhatsApp support.",
    buy1: "Accident damaged vehicles",
    buy2: "Written-off vehicles",
    buy3: "Fire damaged vehicles",
    buy4: "Flood damaged vehicles",
    buy5: "Scrap vehicles",
    buy6: "Vehicles with engine failure",
    buy7: "Vehicles with tow certificates",
    buy8: "Heavily damaged vehicles",
    badge: "About Us",
    title: "Turkey's Trusted Brand in Damaged Vehicle Purchasing",
    subtitle: "With years of automotive experience, we offer the most accurate price and the most reliable service to damaged vehicle owners.",
    ctaQuote: "Get a Free Quote",
    ctaWhatsapp: "Message on WhatsApp",
    storyTitle: "Our Story",
    storyP1: "Oto Grade was founded by a team who saw how complicated and stressful selling a damaged vehicle could be. We realized that accident vehicle owners were stuck between dealerships, tow trucks, and insurers.",
    storyP2: "To solve this problem, we focused on one goal: providing a fast, fair, and transparent sales experience for damaged vehicle owners. Today, we serve every province in Turkey.",
    valuesTitle: "Our Values",
    valuesSubtitle: "We approach every customer with the same care.",
    buyTitle: "What Vehicles Do We Buy?",
    buySubtitle: "We provide quotes for all types of damaged vehicles.",
    step1Title: "Fill Out the Form",
    step2Title: "Our Expert Calls You",
    step3Title: "Pickup and Payment",
    formTitle: "Get a Quick Quote",
    problemsTitle: "What Conditions Are Covered?",
    howTitle: "How It Works?",
    faqTitle: "Frequently Asked Questions",
    relatedTitle: "Related Services",
    contactTitle: "Contact — Oto Grade",
    contactDescription: "Contact Oto Grade. Reach us by phone, WhatsApp, or through the form.",
    phoneCta: "Call by Phone",
    whatsappCta: "Message on WhatsApp",
    whatsappSub: "We reply 7 days a week",
    citiesAria: "Cities served",
    citiesTitle: "Cities We Serve",
    citiesSub: "and all provinces of Turkey",
    howItWorksTitle: "How It Works — Oto Grade",
    howItWorksDescription: "The process of selling a damaged vehicle with Oto Grade. Sell your vehicle in 6 steps, door pickup and fast payment.",
    step1Desc: "Submit your vehicle brand, damage type, city, and phone number via a short form. Non-binding, takes 2 minutes.",
    step1Time: "~2 minutes",
    step2Desc: "Our expert team reviews the information and photos you send and evaluates your vehicle.",
    step2Time: "Same day",
    step3Desc: "After the evaluation, our team will call you to make an offer.",
    step3Time: "Within 1 hour",
    step4Title: "Get Your Offer",
    step4Desc: "Evaluate your fair offer determined according to market conditions. You are not obliged to accept.",
    step4Time: "Same day",
    step5Title: "Plan Delivery and Paperwork",
    step5Desc: "If an agreement is reached, the delivery date and paperwork process are planned together. Our team is with you every step of the way.",
    step5Time: "1-2 days",
    step6Title: "Complete Payment Process",
    step6Desc: "Your payment is made after the vehicle handover and transfer process is completed.",
    step6Time: "Delivery day",
    req1: "Vehicle make and model",
    req2: "Model year",
    req3: "Damage type and description",
    req4: "City and district information",
    req5: "Phone number",
    req6: "Vehicle photos (optional)",
    trust1Title: "Non-Binding",
    trust1Desc: "Getting a quote does not create any obligation.",
    trust2Title: "Transparent Process",
    trust2Desc: "We inform you of every step in advance.",
    trust3Title: "Personal Data is Safe",
    trust3Desc: "Your information is protected under GDPR/KVKK.",
    trust4Title: "Fast Response",
    trust4Desc: "We get back to you within 1 hour.",
    stepsTitle: "6-Step Process",
    stepsSubtitle: "Every step from application to payment.",
    stepsAria: "Process steps",
    reqTitle: "What Information is Needed?",
    reqSubtitle: "Minimum information needed for the application.",
    trustTitle: "Is it Safe?",
    trustSubtitle: "Our process is completely transparent and secure.",
    cityTitleSuffix: "Damaged Vehicle Buyers — Oto Grade",
    heroTitle: "Damaged Vehicle Buyers",
    districtsTitle: "Districts Served",
    typesTitle: "Vehicle Types We Buy",
    nearbyTitle: "Nearby Cities",
    quoteTitle: "Get a Free Quote — Oto Grade",
    quoteDescription: "Get a free, non-binding quote for your damaged vehicle. Fill out the form, our expert team will respond quickly.",
    trust1: "Free evaluation",
    trust2: "Nationwide service",
    trust3: "Fast reply via WhatsApp",
    side1Title: "Free and Non-Binding",
    side1Desc: "You don't pay anything to get a quote. You can change your mind at any time.",
    side2Title: "Response Within 1 Hour",
    side2Desc: "After receiving your application, our expert team will call you as soon as possible.",
    side3Title: "Doorstep Pickup",
    side3Desc: "We pick up your vehicle from its location, we won't leave you stranded.",
    side4Title: "Paperwork Support",
    side4Desc: "Our team is with you every step of the way during transfer and notary transactions.",
    featuresAria: "Highlighted features",
    whyAria: "Why Oto Grade",
    whyTitle: "Why Oto Grade?",
    directContact: "Want to speak directly instead of filling out a form?",
    whatsappAria: "Message on WhatsApp",
    whatsapp: "Message on WhatsApp"
  },
  vehicleTypesPage: {
    schemaTitle: "Damaged Vehicle Types",
    badge: "Vehicle Types",
    title: "We Buy All Types of Damaged Vehicles at Fair Value",
    subtitle: "Accident, written-off, fire-damaged, flood-damaged or broken down, it doesn't matter. Let us know the condition of your vehicle and get a free quote.",
    ctaQuote: "Get a Free Quote",
    ctaWhatsapp: "Message on WhatsApp",
    details: "Detailed Information",
    citiesTitle: "Cities We Serve",
    citiesSubtitle: "On-site pickup service in major cities of Turkey."
  },
  blogDetail: {
    back: "Back to Blog",
    share: "Share this post:"
  },
  blogPage: {
    badge: "Blog",
    title: "Industry News and Guides",
    subtitle: "Up-to-date information on the damaged vehicle industry, vehicle depreciation, and insurance transactions.",
    ctaQuote: "Get a Free Quote",
    ctaWhatsapp: "Message on WhatsApp",
    empty: "There are no blog posts published yet.",
    noImage: "No Image",
    readMore: "Read More"
  },
  privacy: {
    privacyDesc: "Information about Oto Grade's privacy policy and personal data processing.",
    title: "Privacy Policy",
    s1Title: "1. General Information",
    s2Title: "2. Information Collected",
    s2Desc: "The following information may be collected within the scope of our service processes:",
    s2i1: "Name and surname information",
    s2i2: "Phone number",
    s2i3: "City and district information",
    s2i4: "Vehicle information (make, model, year, damage type)",
    s2i5: "Vehicle photos (optional upload)",
    s3Title: "3. Use of Information",
    s3Desc: "The collected information is used only for the following purposes:",
    s3i1: "To prepare a price quote for your vehicle",
    s3i2: "To inform you by calling or messaging",
    s3i3: "To improve our service quality",
    s3i4: "To fulfill legal obligations",
    s4Title: "4. Sharing of Information",
    s4Content: "Your personal data is not shared, sold, or rented to third parties except for legal obligations and requests from official authorities.",
    s5Title: "5. Cookies",
    s5Content: "Our website may use analytical cookies to improve user experience. Google Analytics and Google Ads cookies are used to track anonymous user behavior. You can disable cookies from your browser settings.",
    s6Title: "6. Data Security",
    s6Content: "Industry-standard security measures are applied to protect your personal data. Your data is transmitted over encrypted connections and stored on secure servers.",
    s7Title: "7. Data Retention Period",
    s7Content: "Your personal data is stored within the legal periods from the end of the service purpose. Upon your request, your data can be deleted.",
    s8Title: "8. Your Rights",
    s8Content: "Under the KVKK/GDPR, you have the right to get information, correct, and delete your personal data. You can contact us to exercise these rights.",
    s9Title: "9. Changes",
    s9Content: "This policy may be updated from time to time. Users will be informed of significant changes.",
    privacyTitle: "Privacy Policy — ${SITE_NAME}",
    s1Content: "As ${SITE_NAME}, protecting the privacy of our users is our top priority. This policy explains how information collected when you visit our website or use our services is processed."
  },
  servicePage: {
    step1Desc: "Submit vehicle information via a short form.",
    step2Desc: "Our team will evaluate and give you an offer.",
    step3Desc: "We pick up your vehicle and make your payment.",
    home: "Home",
    services: "Services",
    schemaOffer: "Free quote — non-binding",
    ctaQuote: "Get a Free Quote",
    ctaWhatsapp: "Message on WhatsApp",
    whatsapp: "Message on WhatsApp",
    formSub: "Non-binding · Fast response",
    problemsSub: "We evaluate in any of the following situations.",
    howSub: "Sell your vehicle in 3 steps."
  },
  terms: {
    termsDesc: "Oto Grade website terms of use and service conditions.",
    title: "Terms of Use",
    s1Title: "1. Acceptance",
    s1Content: "By using this website, you agree to the following terms of use. If you do not agree to the terms, please stop using the site.",
    s2Title: "2. Service Description",
    s3Title: "3. Quote Form",
    s3Desc: "The following rules apply to the information submitted via the quote form:",
    s3i1: "The user is responsible for entering real and accurate information",
    s3i2: "Uploaded photos must reflect reality",
    s3i3: "Applications containing misleading information may be excluded from evaluation",
    s3i4: "Form submission does not create an obligation to sell",
    s4Title: "4. Limitation of Liability",
    s5Title: "5. Intellectual Property",
    s6Title: "6. Linked Sites",
    s6Content: "Our website may contain links to third-party sites. We are not responsible for the content and privacy practices of these sites.",
    s7Title: "7. Changes",
    s7Content: "These terms of use may be changed without any notice. Your continued use of the site means you accept the updated terms.",
    s8Title: "8. Governing Law",
    s8Content: "These conditions are subject to the laws of the Republic of Turkey. Istanbul courts are authorized in disputes.",
    termsTitle: "Terms of Use — ${SITE_NAME}",
    s2Content: "${SITE_NAME} is a platform that mediates the purchase of damaged, accident, written-off, and used vehicles. Offers received through the website are non-binding and in the nature of a preliminary evaluation. The final offer is determined after the vehicle is inspected on site.",
    s4Content: "${SITE_NAME} takes utmost care regarding the accuracy, currency, and completeness of the information on the website, but cannot be held responsible for damages that may arise from errors or omissions. Site contents are for informational purposes.",
    s5Content: "All content on this website (texts, images, logos, design) belongs to ${SITE_NAME} and cannot be copied, distributed, or modified without permission."
  },
  kvkk: {
    kvkkDesc: "Oto Grade KVKK Personal Data Protection Law clarification text.",
    title: "KVKK Clarification Text",
    s1Title: "1. Data Controller",
    s2Title: "2. Processed Personal Data",
    s2Desc: "The following personal data are processed within the scope of our services:",
    s2i1: "Name, surname",
    s2i2: "Phone number",
    s2i3: "City and district information",
    s2i4: "Vehicle information (make, model, year, damage type)",
    s3Title: "3. Purpose of Processing Personal Data",
    s3Content: "Your personal data is processed for the purposes of preparing damaged vehicle purchase offers, communicating, and fulfilling legal obligations.",
    s4Title: "4. Transfer of Personal Data",
    s4Content: "Your personal data is not shared with third parties except for legal obligations.",
    s5Title: "5. Your Rights",
    s5Desc: "Under Article 11 of the KVKK, you have the following rights:",
    s5i1: "To learn whether your personal data is processed",
    s5i2: "To request information if your personal data has been processed",
    s5i3: "To request the deletion or destruction of your personal data",
    s6Title: "6. Contact",
    s6Content: "You can contact us to exercise your rights. This text is not a final legal text; legal consultation is recommended.",
    kvkkTitle: "KVKK Clarification Text — ${SITE_NAME}",
    s1Content: "As ${SITE_NAME}, we have prepared this clarification text to inform you about the processing of your personal data under the Personal Data Protection Law (KVKK) No. 6698."
  },
  marketplaceDetail: {
    back: "Back to Listings",
    noImage: "No Image",
    descTitle: "Listing Description",
    noDesc: "No description has been entered for this listing yet.",
    brand: "Brand",
    model: "Model",
    year: "Year",
    damageStatus: "Damage Status",
    whatsapp: "Get Info via WhatsApp",
    adId: "Listing ID:",
    trustTitle: "Oto Grade Guarantee",
    trust1: "Transparent process and fair pricing",
    trust2: "Notary and paperwork support"
  },
  marketplace: {
    badge: "Listings",
    title: "Damaged Vehicles for Sale",
    subtitle: "Choose the one that suits you from our large inventory of damaged vehicles and make an offer right away.",
    searchPlaceholder: "Search make, model, or title...",
    allDamageTypes: "All Damage Types",
    empty: "No vehicles found matching your criteria.",
    noImage: "No Image",
    model: "Model",
    view: "View"
  },
  cityPage: {
    home: "Home",
    cities: "Cities",
    citySchemaName: "Damaged Vehicle Buyers",
    citySchemaLocalBusiness: "Damaged Vehicle Purchasing",
    citySchemaPrice: "Free Quote",
    districtsAria: "districts",
    formSub: "Non-binding · Fast response",
    typesSubtitle: "We provide quotes for all types of damaged vehicles.",
    nearbySubtitle: "We also provide service in neighboring provinces.",
    nearbyCityTag: "Damaged Vehicle"
  },
  thankYou: {
    title: "Application Received",
    desc: "The Oto Grade team will get back to you via phone or WhatsApp shortly. Our average response time is 1 hour.",
    whatsappAria: "Write immediately via WhatsApp",
    whatsapp: "Write immediately via WhatsApp",
    phoneAria: "Call by phone",
    phone: "Call by Phone",
    home: "Return to Home",
    stepsTitle: "Next steps",
    step1: "Our expert will call you within 1 hour.",
    step2: "We will evaluate your vehicle details and offer.",
    step3: "If agreed, we will pick up your vehicle from its location.",
    step4: "Transfer and payment process will be completed."
  },
  notFound: {
    title: "Page Not Found",
    subtitle: "The page you are looking for does not exist or may have been moved.",
    home: "Return to Home",
    quote: "Get a Quote",
    whatsapp: "Message on WhatsApp",
    message: "The page you are looking for may have been moved, deleted, or never existed."
  },
  citiesIndex: {
    home: "Home",
    cities: "Cities",
    listName: "Cities We Serve",
    citySuffix: "Damaged Vehicle Buyers",
    badge: "Cities",
    heroTitle: "Buying Damaged Vehicles from All Over Turkey",
    heroDesc: "No matter where you are, we pick up your accident or broken vehicle from your door with our free towing service and pay in cash immediately.",
    ctaQuote: "Get a Free Quote",
    ctaWhatsappAria: "Message on WhatsApp",
    ctaWhatsapp: "Message on WhatsApp",
    sectionTitle: "Cities We Serve",
    sectionSubtitle: "Select your city below to access the city-specific damaged vehicle purchasing page.",
    districts: "districts",
    getQuote: "Get a Quote"
  }
};

const updated = { ...en, ...translations };
fs.writeFileSync(path, JSON.stringify(updated, null, 2));
