"use client";

import { useState, useRef } from "react";
import { useRouter } from "@/i18n/routing";
import { supabase } from "@/lib/supabase";
import { GradeBadge } from "@/components/marketplace/GradeBadge";
import { DamageBadge } from "@/components/marketplace/DamageBadge";
import { CITIES, CAR_BRANDS, DAMAGE_TYPES } from "@/lib/constants";
import { autoTitle, YEAR_OPTIONS, CURRENT_YEAR } from "@/lib/dealer-utils";
import { DamageGrade, GRADE_DESCRIPTIONS } from "@/types/marketplace";
import { CheckCircle, ChevronRight, ChevronLeft, Upload, X } from "lucide-react";
import { cn } from "@/lib/utils";

const STEPS = ["Araç Bilgileri", "Hasar Bilgileri", "Fiyat & Açıklama", "Fotoğraflar", "Önizleme"];
const GRADES: DamageGrade[] = ["A", "B", "C", "D", "E"];
const FUEL_TYPES = ["benzin", "dizel", "lpg", "elektrik", "hibrit"];
const TRANSMISSIONS = ["manuel", "otomatik"];

type FormState = {
  brand: string; model: string; year: number;
  fuel_type: string; transmission: string; km: string; color: string;
  city: string; district: string;
  damage_type: string[]; damage_grade: DamageGrade | "";
  damage_description: string; has_tramer: boolean; tramer_amount: string;
  asking_price: string; is_price_negotiable: boolean;
  title: string; description: string;
};

const INIT: FormState = {
  brand: "", model: "", year: CURRENT_YEAR,
  fuel_type: "", transmission: "", km: "", color: "",
  city: "", district: "",
  damage_type: [], damage_grade: "",
  damage_description: "", has_tramer: false, tramer_amount: "",
  asking_price: "", is_price_negotiable: false,
  title: "", description: "",
};

export default function IlanEklePage() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<FormState>(INIT);
  const [images, setImages] = useState<File[]>([]);
  const [imageUrls, setImageUrls] = useState<string[]>([]); // after upload
  const [primaryIndex, setPrimaryIndex] = useState(0);
  const [uploading, setUploading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const set = <K extends keyof FormState>(k: K, v: FormState[K]) =>
    setForm((f) => ({ ...f, [k]: v }));

  function toggleDamageType(d: string) {
    set("damage_type",
      form.damage_type.includes(d)
        ? form.damage_type.filter((x) => x !== d)
        : [...form.damage_type, d]
    );
  }

  const autoGeneratedTitle = autoTitle(form.year, form.brand, form.model, form.damage_type);

  function validateStep(): string {
    if (step === 0) {
      if (!form.brand || !form.model || !form.year || !form.city) return "Marka, model, yıl ve şehir zorunludur.";
    }
    if (step === 1) {
      if (!form.damage_grade) return "Otograde derecesini seçin.";
    }
    if (step === 2) {
      if (!form.asking_price || isNaN(Number(form.asking_price))) return "Geçerli bir fiyat girin.";
    }
    if (step === 3) {
      if (images.length < 1) return "En az 1 fotoğraf ekleyin.";
    }
    return "";
  }

  async function next() {
    const e = validateStep();
    if (e) { setError(e); return; }
    setError("");

    // Upload images on step 3 → 4 transition
    if (step === 3 && images.length > 0 && imageUrls.length === 0) {
      setUploading(true);
      try {
        const { data: { session } } = await supabase.auth.getSession();
        if (!session) throw new Error("Oturum bulunamadı.");

        const urls: string[] = [];
        for (const file of images) {
          const fd = new FormData();
          fd.append("file", file);
          fd.append("folder", `listing-${Date.now()}`);
          const res = await fetch("/api/dealer/upload", {
            method: "POST",
            headers: { Authorization: `Bearer ${session.access_token}` },
            body: fd,
          });
          const d = await res.json();
          if (!res.ok) throw new Error(d.error || "Yükleme başarısız.");
          urls.push(d.url);
        }
        setImageUrls(urls);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Fotoğraf yüklenemedi.");
        setUploading(false);
        return;
      }
      setUploading(false);
    }

    setStep((s) => s + 1);
  }

  async function submit() {
    setSubmitting(true);
    setError("");
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) throw new Error("Oturum bulunamadı.");

      const res = await fetch("/api/dealer/listings", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${session.access_token}`,
        },
        body: JSON.stringify({
          brand: form.brand,
          model: form.model,
          year: form.year,
          fuel_type: form.fuel_type || null,
          transmission: form.transmission || null,
          km: form.km ? parseInt(form.km) : null,
          color: form.color || null,
          city: form.city,
          district: form.district || null,
          damage_type: form.damage_type,
          damage_grade: form.damage_grade || null,
          damage_description: form.damage_description || null,
          has_tramer: form.has_tramer,
          tramer_amount: form.tramer_amount ? parseInt(form.tramer_amount) : null,
          asking_price: parseInt(form.asking_price),
          is_price_negotiable: form.is_price_negotiable,
          title: form.title || autoGeneratedTitle,
          images: imageUrls,
          primary_image: imageUrls[primaryIndex] || null,
          status: "pending_review",
        }),
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "İlan oluşturulamadı.");

      router.replace("/bayi-paneli/ilanlarim" as never);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Hata oluştu.");
    }
    setSubmitting(false);
  }

  function addFiles(files: FileList | null) {
    if (!files) return;
    const valid = Array.from(files).filter(
      (f) => f.type.startsWith("image/") && f.size <= 10 * 1024 * 1024
    );
    setImages((prev) => [...prev, ...valid].slice(0, 20));
  }

  return (
    <div className="flex flex-col gap-24 max-w-[720px]">
      <div>
        <h1 className="text-[22px] font-bold text-on-surface tracking-[-0.5px]">Yeni İlan Ekle</h1>
        <p className="text-[13px] text-muted-text mt-4">İlan bilgilerini doldurarak yayınlayın.</p>
      </div>

      {/* Stepper */}
      <div className="flex gap-0 overflow-x-auto pb-2">
        {STEPS.map((s, i) => (
          <div key={s} className="flex items-center shrink-0">
            <div className={cn(
              "flex items-center gap-6 px-10 py-6 rounded-full text-[12px] font-medium transition-colors",
              i === step ? "bg-primary text-white" :
              i < step ? "bg-green-100 text-green-700" :
              "text-muted-text"
            )}>
              {i < step ? <CheckCircle size={13} /> : <span className="w-[16px] h-[16px] flex items-center justify-center">{i + 1}</span>}
              <span className="hidden md:inline">{s}</span>
            </div>
            {i < STEPS.length - 1 && <div className="w-[20px] h-px bg-border-default mx-2" />}
          </div>
        ))}
      </div>

      <div className="bg-surface-container-lowest border border-[0.5px] border-border-default rounded-card p-24">
        {error && <div className="bg-red-50 text-red-600 text-[13px] p-12 rounded-lg mb-20">{error}</div>}

        {/* Step 0: Vehicle info */}
        {step === 0 && (
          <div className="flex flex-col gap-16">
            <h2 className="text-[16px] font-semibold text-on-surface mb-4">Araç Bilgileri</h2>
            <div className="grid grid-cols-2 gap-14">
              <FormField label="Marka *">
                <select value={form.brand} onChange={(e) => set("brand", e.target.value)} className={selectCls}>
                  <option value="">Seçin...</option>
                  {CAR_BRANDS.map((b) => <option key={b} value={b}>{b}</option>)}
                </select>
              </FormField>
              <FormField label="Model *">
                <input value={form.model} onChange={(e) => set("model", e.target.value)} placeholder="Örn: 320i" className={inputCls} />
              </FormField>
              <FormField label="Yıl *">
                <select value={form.year} onChange={(e) => set("year", Number(e.target.value))} className={selectCls}>
                  {YEAR_OPTIONS.map((y) => <option key={y} value={y}>{y}</option>)}
                </select>
              </FormField>
              <FormField label="KM">
                <input type="number" value={form.km} onChange={(e) => set("km", e.target.value)} placeholder="Ör: 120000" className={inputCls} />
              </FormField>
              <FormField label="Yakıt">
                <select value={form.fuel_type} onChange={(e) => set("fuel_type", e.target.value)} className={selectCls}>
                  <option value="">Seçin...</option>
                  {FUEL_TYPES.map((f) => <option key={f} value={f} className="capitalize">{f}</option>)}
                </select>
              </FormField>
              <FormField label="Vites">
                <select value={form.transmission} onChange={(e) => set("transmission", e.target.value)} className={selectCls}>
                  <option value="">Seçin...</option>
                  {TRANSMISSIONS.map((t) => <option key={t} value={t} className="capitalize">{t}</option>)}
                </select>
              </FormField>
              <FormField label="Renk">
                <input value={form.color} onChange={(e) => set("color", e.target.value)} placeholder="Ör: Siyah" className={inputCls} />
              </FormField>
              <FormField label="Şehir *">
                <select value={form.city} onChange={(e) => set("city", e.target.value)} className={selectCls}>
                  <option value="">Seçin...</option>
                  {Object.entries(CITIES).map(([, label]) => <option key={label} value={label}>{label}</option>)}
                </select>
              </FormField>
              <FormField label="İlçe">
                <input value={form.district} onChange={(e) => set("district", e.target.value)} placeholder="İlçe (isteğe bağlı)" className={inputCls} />
              </FormField>
            </div>
          </div>
        )}

        {/* Step 1: Damage info */}
        {step === 1 && (
          <div className="flex flex-col gap-20">
            <h2 className="text-[16px] font-semibold text-on-surface">Hasar Bilgileri</h2>

            {/* Grade selector */}
            <div>
              <label className="text-[13px] font-medium text-on-surface block mb-10">Otograde Derecesi *</label>
              <div className="grid grid-cols-5 gap-8">
                {GRADES.map((g) => (
                  <button
                    key={g}
                    type="button"
                    onClick={() => set("damage_grade", g)}
                    className={cn(
                      "flex flex-col items-center gap-8 p-12 rounded-card border-2 transition-all",
                      form.damage_grade === g ? "border-primary bg-primary/5" : "border-border-default hover:border-primary/40"
                    )}
                  >
                    <GradeBadge grade={g} size="lg" />
                    <span className="text-[10px] text-muted-text text-center leading-tight">{GRADE_DESCRIPTIONS[g].split(" — ")[0]}</span>
                  </button>
                ))}
              </div>
              {form.damage_grade && (
                <p className="text-[12px] text-muted-text mt-8 bg-surface p-10 rounded-lg">
                  <strong>Grade {form.damage_grade}:</strong> {GRADE_DESCRIPTIONS[form.damage_grade]}
                </p>
              )}
            </div>

            {/* Damage types */}
            <div>
              <label className="text-[13px] font-medium text-on-surface block mb-10">Hasar Türleri</label>
              <div className="flex flex-wrap gap-8">
                {DAMAGE_TYPES.map((d) => (
                  <button
                    key={d}
                    type="button"
                    onClick={() => toggleDamageType(d)}
                    className={cn(
                      "px-12 py-8 rounded-full border text-[12px] font-medium transition-colors",
                      form.damage_type.includes(d)
                        ? "border-primary bg-primary/10 text-primary"
                        : "border-border-default text-muted-text hover:border-primary/40"
                    )}
                  >
                    {d}
                  </button>
                ))}
              </div>
            </div>

            {/* Tramer */}
            <div className="flex flex-col gap-12">
              <label className="flex items-center gap-10 cursor-pointer">
                <input type="checkbox" checked={form.has_tramer} onChange={(e) => set("has_tramer", e.target.checked)} className="w-[16px] h-[16px] accent-primary" />
                <span className="text-[13px] font-medium text-on-surface">Tramer kaydı var</span>
              </label>
              {form.has_tramer && (
                <div className="ml-26">
                  <input
                    type="number"
                    placeholder="Tramer tutarı (TL)"
                    value={form.tramer_amount}
                    onChange={(e) => set("tramer_amount", e.target.value)}
                    className={inputCls}
                  />
                </div>
              )}
            </div>

            {/* Damage description */}
            <FormField label="Hasar Açıklaması">
              <textarea
                rows={5}
                placeholder="Hasarı detaylı açıklayın..."
                value={form.damage_description}
                onChange={(e) => set("damage_description", e.target.value)}
                className={cn(inputCls, "resize-none")}
              />
            </FormField>
          </div>
        )}

        {/* Step 2: Price & description */}
        {step === 2 && (
          <div className="flex flex-col gap-16">
            <h2 className="text-[16px] font-semibold text-on-surface">Fiyat & Açıklama</h2>
            <FormField label="İstenen Fiyat (TL) *">
              <input
                type="number"
                value={form.asking_price}
                onChange={(e) => set("asking_price", e.target.value)}
                placeholder="Ör: 150000"
                className={inputCls}
              />
            </FormField>
            <label className="flex items-center gap-10 cursor-pointer">
              <input type="checkbox" checked={form.is_price_negotiable} onChange={(e) => set("is_price_negotiable", e.target.checked)} className="w-[16px] h-[16px] accent-primary" />
              <span className="text-[13px] text-on-surface">Pazarlık payı var</span>
            </label>

            <FormField label="İlan Başlığı">
              <input
                value={form.title}
                onChange={(e) => set("title", e.target.value)}
                placeholder={autoGeneratedTitle}
                className={inputCls}
              />
              <p className="text-[11px] text-muted-text mt-4">Boş bırakırsanız otomatik oluşturulur: &ldquo;{autoGeneratedTitle}&rdquo;</p>
            </FormField>

            <FormField label="Ek Açıklama">
              <textarea
                rows={5}
                value={form.description}
                onChange={(e) => set("description", e.target.value)}
                placeholder="Alıcıya iletmek istediğiniz ek bilgiler..."
                className={cn(inputCls, "resize-none")}
              />
            </FormField>
          </div>
        )}

        {/* Step 3: Photos */}
        {step === 3 && (
          <div className="flex flex-col gap-16">
            <h2 className="text-[16px] font-semibold text-on-surface">Fotoğraflar</h2>
            <p className="text-[13px] text-muted-text">En az 1, en fazla 20 fotoğraf yükleyebilirsiniz. (max 10 MB / fotoğraf)</p>

            {/* Drop zone */}
            <div
              className="border-2 border-dashed border-border-default rounded-card p-32 flex flex-col items-center gap-12 cursor-pointer hover:border-primary transition-colors"
              onClick={() => fileInputRef.current?.click()}
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => { e.preventDefault(); addFiles(e.dataTransfer.files); }}
            >
              <Upload size={28} className="text-muted-text" />
              <p className="text-[13px] text-muted-text">Fotoğrafları sürükleyin veya tıklayın</p>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/jpeg,image/png,image/webp"
                multiple
                className="hidden"
                onChange={(e) => addFiles(e.target.files)}
              />
            </div>

            {/* Preview grid */}
            {images.length > 0 && (
              <div>
                <p className="text-[12px] text-muted-text mb-10">İlk fotoğraf kapak fotoğrafıdır. Sürükleyerek sıralayın.</p>
                <div className="grid grid-cols-4 md:grid-cols-5 gap-10">
                  {images.map((file, i) => (
                    <div
                      key={i}
                      className={cn(
                        "relative aspect-square rounded-lg overflow-hidden border-2 cursor-pointer",
                        i === primaryIndex ? "border-primary" : "border-transparent"
                      )}
                      onClick={() => setPrimaryIndex(i)}
                    >
                      <img src={URL.createObjectURL(file)} alt="" className="w-full h-full object-cover" />
                      {i === primaryIndex && (
                        <div className="absolute top-4 left-4 bg-primary text-white text-[9px] font-semibold px-4 py-2 rounded">
                          KAPAK
                        </div>
                      )}
                      <button
                        onClick={(e) => { e.stopPropagation(); setImages((imgs) => imgs.filter((_, j) => j !== i)); }}
                        className="absolute top-4 right-4 w-[18px] h-[18px] bg-black/60 text-white rounded-full flex items-center justify-center hover:bg-black/80"
                      >
                        <X size={10} />
                      </button>
                    </div>
                  ))}
                  {images.length < 20 && (
                    <button
                      onClick={() => fileInputRef.current?.click()}
                      className="aspect-square border-2 border-dashed border-border-default rounded-lg flex items-center justify-center hover:border-primary transition-colors"
                    >
                      <Plus size={20} className="text-muted-text" />
                    </button>
                  )}
                </div>
              </div>
            )}

            {uploading && (
              <div className="bg-blue-50 text-blue-700 text-[13px] p-12 rounded-lg">
                Fotoğraflar yükleniyor... Lütfen bekleyin.
              </div>
            )}
          </div>
        )}

        {/* Step 4: Preview */}
        {step === 4 && (
          <div className="flex flex-col gap-20">
            <h2 className="text-[16px] font-semibold text-on-surface">Önizleme & Yayınla</h2>

            <div className="bg-surface rounded-card border border-[0.5px] border-border-default overflow-hidden">
              {/* Preview card */}
              {(imageUrls[0] || images[0]) && (
                <div className="aspect-video">
                  <img
                    src={imageUrls[primaryIndex] || URL.createObjectURL(images[primaryIndex])}
                    alt=""
                    className="w-full h-full object-cover"
                  />
                </div>
              )}
              <div className="p-20">
                <div className="flex items-start gap-12 mb-14">
                  <GradeBadge grade={form.damage_grade || null} size="md" />
                  <div>
                    <h3 className="text-[17px] font-bold text-on-surface">{form.title || autoGeneratedTitle}</h3>
                    <p className="text-[12px] text-muted-text mt-2">{form.city} · {form.year} · {form.km ? `${Number(form.km).toLocaleString("tr-TR")} km` : ""}</p>
                  </div>
                </div>
                {form.damage_type.length > 0 && (
                  <div className="flex flex-wrap gap-6 mb-14">
                    {form.damage_type.map((d) => <DamageBadge key={d} type={d} />)}
                  </div>
                )}
                <div className="text-[20px] font-bold text-primary">
                  {form.asking_price ? `${parseInt(form.asking_price).toLocaleString("tr-TR")} TL` : "—"}
                  {form.is_price_negotiable && <span className="text-[12px] text-muted-text font-normal ml-8">Pazarlık payı var</span>}
                </div>
              </div>
            </div>

            <div className="bg-amber-50 border border-amber-200 rounded-lg p-14 text-[12px] text-amber-700">
              İlan gönderildikten sonra admin incelemesine alınacak ve onaylanınca yayına girecek.
            </div>

            <button
              onClick={submit}
              disabled={submitting}
              className="w-full bg-primary text-white py-14 rounded-btn text-[14px] font-bold hover:opacity-90 transition-opacity disabled:opacity-60"
            >
              {submitting ? "Gönderiliyor..." : "İlanı Gönder"}
            </button>
          </div>
        )}

        {/* Navigation */}
        <div className="flex items-center justify-between mt-24 pt-20 border-t border-[0.5px] border-border-default">
          {step > 0 ? (
            <button onClick={() => { setError(""); setStep((s) => s - 1); }} className="flex items-center gap-6 text-[13px] text-muted-text hover:text-on-surface">
              <ChevronLeft size={16} /> Geri
            </button>
          ) : <div />}

          {step < STEPS.length - 1 && (
            <button
              onClick={next}
              disabled={uploading}
              className="flex items-center gap-8 bg-primary text-white px-24 py-11 rounded-btn text-[13px] font-semibold hover:opacity-90 disabled:opacity-60"
            >
              {uploading ? "Yükleniyor..." : "Devam Et"} <ChevronRight size={16} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

const inputCls = "w-full px-14 py-11 bg-surface border border-[0.5px] border-border-default rounded-input text-[13px] text-on-surface outline-none focus:border-primary transition-colors";
const selectCls = "w-full px-14 py-11 bg-surface border border-[0.5px] border-border-default rounded-input text-[13px] text-on-surface outline-none focus:border-primary transition-colors";

function FormField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-6">
      <label className="text-[12px] font-semibold text-on-surface uppercase tracking-wide">{label}</label>
      {children}
    </div>
  );
}

// Placeholder for Plus icon usage in photos grid
function Plus({ size, className }: { size: number; className?: string }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5} className={className}><path d="M12 5v14M5 12h14" strokeLinecap="round" /></svg>;
}
